// 简体中文播放器日志文本配置
// 只负责 Playback Log、运行时状态、Details 和 Suggestion 的中文化。
// SEO 页面内容仍由各语言页面配置单独维护，不通过这里处理。
export const zhCNPlayerLogText = {
  labels: {
    statusPrefix: '状态',
    statusSeparator: '：',
    statusEnd: '。',
    reportTitle: 'MetisTools 播放诊断报告',
    tool: '工具',
    urlType: '链接类型',
    engine: '播放引擎',
    status: '状态',
    mainError: '主要错误',
    warnings: '警告',
    startedAt: '开始时间',
    sourceUrl: '源链接',
    browser: '浏览器',
    log: '日志',
    noLogLines: '暂无播放诊断记录。',
    none: '无',
    notStarted: '尚未开始',
    details: '详情',
    suggestion: '建议',
    rawLog: '原始日志',
    clearLog: '清空',
    copyLog: '复制日志',
    showSourceLog: '英文日志',
    showLocalizedLog: '中文日志',
    showSourceLogTitle: '切换为英文原文，方便搜索错误。当前日志会立即切换，无需清空。',
    showLocalizedLogTitle: '切换回中文日志。当前日志会立即切换，无需清空。',
  },
  levels: {
    INFO: '信息',
    SUCCESS: '成功',
    WARNING: '警告',
    ERROR: '错误',
    DEBUG: '调试',
  },
  statuses: {
    Ready: '就绪',
    Loading: '加载中',
    Playing: '播放中',
    Failed: '失败',
    Completed: '已完成',
    Buffering: '缓冲中',
    Stalled: '卡顿',
    'Loading slowly': '加载较慢',
  },
  messages: {
    Copied: '已复制',
    'Log cleared. Paste a public or authorized link, then click Play to start a new diagnostic session.': '日志已清空。请粘贴公开或已授权链接，然后点击播放开始新的诊断会话。',
    'Diagnostic session started.': '诊断会话已开始。',
    'Triggered by form submit. URL is hidden from the report for privacy.': '由表单提交触发。为了保护隐私，报告中会隐藏 URL。',
    'Triggered by placeholder button. URL is hidden from the report for privacy.': '由播放器按钮触发。为了保护隐私，报告中会隐藏 URL。',
    'Triggered by placeholder Play button. URL is hidden from the report for privacy.': '由播放器占位区播放按钮触发。为了保护隐私，报告中会隐藏 URL。',
    'Triggered by main Play button. URL is hidden from the report for privacy.': '由主播放按钮触发。为了保护隐私，报告中会隐藏 URL。',
    'Access boundary notice.': '访问边界提示。',
    'This tool does not bypass CORS, DRM, private access controls, copyright restrictions, token rules, or source website permissions.': '本工具不会绕过 CORS、DRM、私有访问控制、版权限制、token 规则或来源网站权限。',
    'If you own the source server, enable CORS for playlists, manifests, media files, and media segments. Allow this site origin for GET, HEAD, and OPTIONS requests, and expose Content-Length, Content-Range, and Accept-Ranges when Range requests are used.': '如果你拥有源服务器，请为播放列表、清单、媒体文件和媒体分片启用 CORS。允许本站来源发起 GET、HEAD、OPTIONS 请求；使用 Range 请求时，还需要暴露 Content-Length、Content-Range 和 Accept-Ranges。',

    'Loading HLS playback engine.': '正在加载 HLS 播放引擎。',
    'hls.js is loaded only when this browser needs it.': '仅在当前浏览器需要时加载 hls.js。',
    'Native HLS support detected.': '检测到浏览器原生 HLS 支持。',
    'The browser can play HLS without hls.js. This is common in Safari.': '浏览器可以不依赖 hls.js 直接播放 HLS，这在 Safari 中较常见。',
    'Setting native video source.': '正在设置原生视频源。',
    'native HLS will use the browser built-in media pipeline.': '原生 HLS 将使用浏览器内置媒体管线。',
    'HLS engine attached to the video element.': 'HLS 引擎已绑定到视频元素。',
    'The browser is ready to receive the HLS media source.': '浏览器已准备接收 HLS 媒体源。',
    'Loading HLS manifest.': '正在加载 HLS 清单。',
    'The player is requesting the M3U8 playlist.': '播放器正在请求 M3U8 播放列表。',
    'HLS manifest loaded.': 'HLS 清单已加载。',
    'HLS manifest parsed.': 'HLS 清单解析完成。',
    'Unknown number of variant streams found.': '发现未知数量的变体流。',
    'No quality levels available for adaptive playback.': '没有发现可用于自适应播放的清晰度级别。',
    'HLS quality switched.': 'HLS 清晰度已切换。',
    'Adaptive bitrate selection is working.': '自适应码率选择正在工作。',
    'Adaptive bitrate rendering is working.': '自适应码率渲染正在工作。',
    'First HLS media segment loaded.': '第一个 HLS 媒体分片已加载。',
    'Segment requests are reachable from this browser.': '当前浏览器可以访问媒体分片请求。',
    'Additional segment logs are hidden to keep the report readable.': '为保持报告可读，后续分片日志已隐藏。',
    'Trying to recover from a fatal HLS network error.': '正在尝试从严重 HLS 网络错误中恢复。',
    'hls.js will retry loading the stream.': 'hls.js 会重试加载该视频流。',
    'Trying to recover from a fatal HLS media error.': '正在尝试从严重 HLS 媒体错误中恢复。',
    'hls.js will attempt media recovery once.': 'hls.js 会尝试进行一次媒体恢复。',
    'HLS playback stopped after an unrecoverable error.': 'HLS 播放因不可恢复错误停止。',
    'HLS playback failed.': 'HLS 播放失败。',
    'HLS playback warning.': 'HLS 播放可能有问题。',
    'Check whether the stream is public, authorized, and accessible from the browser.': '请确认视频流公开、已授权，并允许浏览器访问。',
    'HLS playback engine failed to initialize.': 'HLS 播放引擎初始化失败。',
    'Refresh the page or try a browser with MediaSource Extensions support.': '请刷新页面，或尝试使用支持 MediaSource Extensions 的浏览器。',
    'HLS playback is not supported in this browser.': '当前浏览器不支持 HLS 播放。',
    'hls.js reported that MediaSource Extensions are unavailable.': 'hls.js 报告当前浏览器不可用 MediaSource Extensions。',
    'Try Safari for native HLS, or use Chrome, Edge, or Firefox with MediaSource Extensions support.': '可以尝试 Safari 原生 HLS，或使用支持 MediaSource Extensions 的 Chrome、Edge、Firefox。',
    'HLS manifest could not be loaded.': '无法加载 HLS 播放列表。',
    'HLS media segment could not be loaded.': '无法加载 HLS 视频分片。',
    'HLS playlist request may be blocked by browser CORS or access policy.': '浏览器可能被 CORS 或访问策略拦截，无法读取 HLS 播放列表。',
    'HLS media segment request may be blocked by browser CORS or access policy.': '浏览器可能被 CORS 或访问策略拦截，无法读取 HLS 视频分片。',
    'HLS key request may be blocked by browser CORS or access policy.': '浏览器可能被 CORS 或访问策略拦截，无法读取 HLS 密钥。',
    'HLS resource request may be blocked by browser CORS or access policy.': '浏览器可能被 CORS 或访问策略拦截，无法读取 HLS 资源。',
    'HLS playlist request was denied by the source server.': 'HLS 播放列表请求被源服务器拒绝。',
    'HLS media segment request was denied by the source server.': 'HLS 媒体分片请求被源服务器拒绝。',
    'HLS key request was denied by the source server.': 'HLS 密钥请求被源服务器拒绝。',
    'HLS resource request was denied by the source server.': 'HLS 资源请求被源服务器拒绝。',
    'Check whether the link is public or authorized, whether signed tokens have expired, and whether the source allows browser playback from this site.': '请检查权限、token 是否过期，以及来源是否允许本站播放。',
    'HLS playlist was not found.': '未找到 HLS 播放列表。',
    'HLS media segment was not found.': '未找到 HLS 媒体分片。',
    'HLS key was not found.': '未找到 HLS 密钥。',
    'HLS resource was not found.': '未找到 HLS 资源。',
    'Check whether the playlist or segment URL is correct, still available, and not generated by an expired temporary link.': '请检查播放列表或分片 URL 是否正确、仍然可用，并确认不是由已过期的临时链接生成。',
    'HLS playlist server error detected.': 'HLS 播放列表服务器返回错误。',
    'HLS media segment server error detected.': 'HLS 视频分片服务器返回错误。',
    'HLS key server error detected.': '检测到 HLS 密钥服务器错误。',
    'HLS resource server error detected.': 'HLS 资源服务器返回错误。',
    'The origin server or CDN returned a server error. Retry later or check the source server logs if you own the stream.': '源服务器或 CDN 返回了服务器错误。请稍后重试；如果你拥有该视频流，请检查源服务器日志。',
    'Verify that the M3U8 URL is public, not expired, and returns a valid playlist with CORS enabled.': '请确认 M3U8 URL 公开、未过期，并且返回启用 CORS 的有效播放列表。',
    'HLS manifest could not be parsed.': 'HLS 播放列表格式不正确。',
    'Check whether the playlist format is valid M3U8 and not an HTML error page, login page, redirect page, or CDN error page.': '请检查播放列表是否为有效 M3U8 格式，而不是 HTML 错误页、登录页、重定向页或 CDN 错误页。',
    'Check segment URLs, CDN availability, CORS headers, token expiry, geo restrictions, and whether relative segment paths resolve correctly.': '请检查分片 URL、CDN 可用性、CORS 响应头、token 是否过期、地区限制，以及相对分片路径是否能正确解析。',
    'HLS buffering issue detected.': 'HLS 缓冲时间过长。',
    'Try another network or stream variant. The server may be slow, missing segments, using too high a bitrate, or delaying live segments.': '请尝试其他网络或清晰度变体。服务器可能响应较慢、分片缺失、码率过高，或直播分片延迟生成。',
    'HLS DRM or key-system issue detected.': '这个 HLS 流可能需要 DRM 或密钥授权。',
    'This browser player cannot play protected streams without the required DRM license flow.': '没有所需的 DRM 许可流程时，当前浏览器播放器无法播放受保护的视频流。',
    'HLS media decode issue detected.': '浏览器无法解码这个 HLS 视频。',
    'Check codecs, container compatibility, browser support, and whether the stream uses unsupported audio/video tracks.': '请检查编码、容器兼容性、浏览器支持情况，以及视频流是否使用了不受支持的音频或视频轨道。',
    'HLS network issue detected.': 'HLS 网络请求失败。',
    'Check server availability, CORS headers, redirects, signed URL expiry, mixed content, and ad-blocking or corporate network filters.': '请检查服务器可用性、CORS 响应头、重定向、签名 URL 是否过期、混合内容，以及广告拦截或企业网络过滤。',

    'Playback requested.': '已请求播放。',
    'hls.js asked the browser to start playback.': 'hls.js 已请求浏览器开始播放。',
    'native HLS asked the browser to start playback.': '原生 HLS 已请求浏览器开始播放。',
    'HLS asked the browser to start playback.': 'HLS 已请求浏览器开始播放。',
    'Playback request accepted by the browser.': '浏览器已接受播放请求。',
    'Playback is already active. Media events confirm the current playing state.': '播放已处于活动状态，媒体事件已确认当前正在播放。',
    'The browser accepted the user click. Playback state will be confirmed by media events.': '浏览器已接受用户点击，播放状态会通过媒体事件继续确认。',
    'Browser blocked automatic playback start.': '浏览器阻止了自动开始播放。',
    'The source is loaded. Use the video controls to start playback, or click Play again after the stream is ready.': '来源已加载。请使用视频控件开始播放，或在流准备好后再次点击播放。',
    'The browser rejected the playback request.': '浏览器拒绝了播放请求。',
    'Click Play again, check browser autoplay rules, or verify that the media format is supported.': '请再次点击播放，检查浏览器自动播放规则，或确认媒体格式受支持。',
    'Source loaded. Use the video controls to start playback.': '来源已加载。请使用视频控件开始播放。',
    'The browser could not play this media source.': '浏览器无法播放该媒体源。',
    'Browser started loading media metadata.': '浏览器开始加载媒体元数据。',
    'The media element accepted the source and began loading.': '媒体元素已接受来源并开始加载。',
    'Media metadata loaded.': '媒体元数据已加载。',
    'First media frame is available.': '首个媒体画面可用。',
    'The browser decoded enough data to render the first frame.': '浏览器已解码足够数据来显示首帧。',
    'Browser can start playback.': '浏览器可以开始播放。',
    'The media source passed the browser compatibility check.': '媒体源通过了浏览器兼容性检查。',
    'Playback started successfully.': '播放已成功开始。',
    'Playback started.': '播放已开始。',
    'The media is actively playing in the browser.': '媒体正在浏览器中播放。',
    'Playback is continuing normally.': '播放正在正常继续。',
    'Playback paused.': '播放已暂停。',
    'This may be caused by the user, browser, or player state.': '这可能由用户操作、浏览器或播放器状态引起。',
    'Seeking started.': '开始跳转播放位置。',
    'The browser is moving to another playback position.': '浏览器正在移动到新的播放位置。',
    'Seeking finished.': '播放位置跳转完成。',
    'The browser reached the requested playback position.': '浏览器已到达请求的播放位置。',
    'Playback reached the end of the media.': '播放已到达媒体末尾。',
    'Playback ended.': '播放结束。',
    'The media played to completion.': '媒体已播放完成。',
    'Playback is waiting for more media data.': '播放正在等待更多媒体数据。',
    'Playback is waiting for more data.': '播放正在等待更多数据。',
    'The browser reported a sustained buffering state. This can be caused by network delay, server delay, CORS restrictions, missing media segments, expired signed segment URLs, or bitrate higher than the current connection can sustain.': '浏览器报告持续缓冲状态。可能原因包括网络延迟、服务器延迟、CORS 限制、媒体分片缺失、签名分片 URL 过期，或码率高于当前连接可承载范围。',
    'Playback appears stalled.': '播放可能出现卡顿。',
    'The browser has not advanced playback for more than 20 seconds and appears to be waiting for media data.': '浏览器播放进度超过 20 秒没有推进，看起来正在等待媒体数据。',
    'Check for missing segments, CORS-blocked segment requests, token expiry, CDN latency, or an overloaded source server.': '请检查媒体分片是否缺失、分片请求是否被 CORS 阻止、token 是否过期、CDN 是否延迟，或源服务器是否过载。',
    'Playback started but appears stalled after repeated checks.': '播放多次检查后仍像是卡住了。',
    'Media metadata is taking longer than expected.': '媒体仍在加载。',
    'The browser has not received playable metadata yet. Common causes include CORS, private or expired URLs, missing MIME type, slow CDN response, unsupported redirects, or server availability.': '浏览器尚未收到可播放的元数据。常见原因包括 CORS 限制、私有或已过期 URL、缺少 MIME 类型、CDN 响应较慢、不支持的重定向，或服务器不可用。',
    'If you own the source, verify CORS, Content-Type, Range support for MP4, and that the manifest or media file is publicly reachable.': '如果你拥有该视频源，请检查 CORS、Content-Type、MP4 的 Range 支持，并确认清单或媒体文件可以被公开访问。',
    'Metadata has not loaded yet. Check CORS, network, MIME type, permissions, and server availability.': '元数据尚未加载。请检查 CORS、网络、MIME 类型、访问权限和服务器可用性。',
    'Playback did not become ready in time.': '播放无法开始。',
    'The browser did not receive enough compatible media data within 20 seconds. This can happen when CORS blocks browser requests, the source is private or expired, the server returns HTML instead of media, MIME type is wrong, codecs are unsupported, or Range requests fail.': '浏览器在 20 秒内没有收到足够的兼容媒体数据。可能原因包括 CORS 阻止浏览器请求、来源为私有或已过期、服务器返回 HTML 而不是媒体内容、MIME 类型错误、编码不受支持，或 Range 请求失败。',
    'Check whether the link is public, CORS allows browser access, codecs are supported, MP4 Range requests work, and the source server is responding with the expected media content.': '请检查链接是否公开、CORS 是否允许浏览器访问、编码是否受支持、MP4 Range 请求是否正常，以及源服务器是否返回预期的媒体内容。',

    'MEDIA_ERR_ABORTED: playback was aborted by the user or browser.': 'MEDIA_ERR_ABORTED：播放被用户或浏览器中止。',
    'MEDIA_ERR_NETWORK: a network error interrupted media loading.': 'MEDIA_ERR_NETWORK：网络错误中断了媒体加载。',
    'MEDIA_ERR_DECODE: the browser could not decode the media. Codec or file corruption is likely.': 'MEDIA_ERR_DECODE：浏览器无法解码媒体，可能是编码不兼容或文件损坏。',
    'MEDIA_ERR_SRC_NOT_SUPPORTED: the source or MIME type is not supported by this browser.': 'MEDIA_ERR_SRC_NOT_SUPPORTED：浏览器无法播放这个来源或格式。',
    'Unknown native video error.': '未知的浏览器原生视频错误。',
    'Check server availability, CORS headers, signed URL expiry, redirects, mixed content, and network connectivity.': '请检查服务器可用性、CORS 响应头、签名 URL 是否过期、重定向、混合内容和网络连接。',
    'Check whether the file uses browser-supported video and audio codecs and is not corrupted or partially uploaded.': '请检查文件是否使用浏览器支持的视频和音频编码，并确认文件没有损坏或只上传了一部分。',
    'Try a public MP4 file or verify that this browser supports the media format, MIME type, codec, and Range request behavior.': '请尝试公开 MP4 文件，或确认当前浏览器支持该媒体格式、MIME 类型、编码和 Range 请求行为。',
    'Check whether the URL is public, authorized, served with correct CORS and MIME headers, and compatible with this browser.': '请检查 URL 是否公开或已授权，是否提供正确的 CORS 和 MIME 响应头，并且是否兼容当前浏览器。',
    'Failed to load because no supported source was found.': '加载失败：没有找到浏览器支持的媒体来源。',
    'Failed to load because no supported source was found': '加载失败：没有找到浏览器支持的媒体来源。',
    'No supported source was found.': '没有找到浏览器支持的媒体来源。',
    'No supported source was found': '没有找到浏览器支持的媒体来源。',
    'The element has no supported sources.': '该视频元素没有可用的受支持媒体来源。',
    'The element has no supported sources': '该视频元素没有可用的受支持媒体来源。',
    MEDIA_ERR_SRC_NOT_SUPPORTED: 'MEDIA_ERR_SRC_NOT_SUPPORTED：当前浏览器不支持该媒体来源。',
    '/MEDIA_ERR_SRC_NOT_SUPPORTED': 'MEDIA_ERR_SRC_NOT_SUPPORTED：当前浏览器不支持该媒体来源。',
    'The media could not be loaded, either because the server or network failed or because the format is not supported.': '媒体无法加载，可能是服务器或网络失败，也可能是媒体格式不受当前浏览器支持。',
    'Technical details: unknown error': '技术详情：未知错误',
    'Technical details: playback must be started from the video controls': '技术详情：需要通过视频控件开始播放',
    'Technical details: browser blocked playback or unsupported media': '技术详情：浏览器阻止播放或媒体不受支持',
    'Technical details: Failed to load because no supported source was found.': '技术详情：加载失败，没有找到浏览器支持的媒体来源。',
    'Technical details: Failed to load because no supported source was found': '技术详情：加载失败，没有找到浏览器支持的媒体来源。',
    'Technical details: No supported source was found.': '技术详情：没有找到浏览器支持的媒体来源。',
    'Technical details: The element has no supported sources.': '技术详情：该视频元素没有可用的受支持媒体来源。',
    'Technical details: MEDIA_ERR_SRC_NOT_SUPPORTED': '技术详情：MEDIA_ERR_SRC_NOT_SUPPORTED，当前浏览器不支持该媒体来源。',
    'Technical details: /MEDIA_ERR_SRC_NOT_SUPPORTED': '技术详情：MEDIA_ERR_SRC_NOT_SUPPORTED，当前浏览器不支持该媒体来源。',
    'Technical details: The media could not be loaded, either because the server or network failed or because the format is not supported.': '技术详情：媒体无法加载，可能是服务器或网络失败，也可能是媒体格式不受当前浏览器支持。',

    'DASH playback engine failed to initialize.': 'DASH 播放引擎初始化失败。',
    'Try Chrome, Edge or Firefox, and make sure the MPD manifest is public and valid.': '请尝试 Chrome、Edge 或 Firefox，并确认 MPD 清单公开且有效。',
    'DASH playback is not supported in this browser.': '当前浏览器不支持 DASH 播放。',
    'dash.js requires MediaSource Extensions, but this browser does not expose a compatible API.': 'dash.js 需要 MediaSource Extensions，但当前浏览器没有提供兼容 API。',
    'Try Chrome, Edge, or Firefox for MPEG-DASH playback.': '请使用 Chrome、Edge 或 Firefox 播放 MPEG-DASH。',
    'DASH manifest loaded.': 'DASH 清单已加载。',
    'The MPD file was downloaded and accepted by dash.js.': 'MPD 文件已下载并被 dash.js 接受。',
    'DASH stream initialized.': 'DASH 视频流已初始化。',
    'The MPD manifest contains playable stream information.': 'MPD 清单包含可播放的视频流信息。',
    'DASH playback started.': 'DASH 播放已开始。',
    'The browser started rendering the stream.': '浏览器已开始渲染视频流。',
    'DASH playback paused.': 'DASH 播放已暂停。',
    'Playback was paused by the user, browser, or player state.': '播放被用户、浏览器或播放器状态暂停。',
    'DASH buffer is empty.': 'DASH 缓冲区为空。',
    'The player is waiting for more media data. This can be caused by slow network, missing segments, or high bitrate.': '播放器正在等待更多媒体数据。可能原因包括网络较慢、分片缺失或码率过高。',
    'DASH buffer loaded.': 'DASH 缓冲已加载。',
    'Enough media data is available to continue playback.': '已有足够媒体数据可继续播放。',
    'DASH quality rendered.': 'DASH 清晰度已渲染。',
    'Quality metadata was not provided by dash.js, but this is not a playback error.': 'dash.js 没有提供清晰度元数据，但这不是播放错误。',
    'Initializing DASH engine.': '正在初始化 DASH 引擎。',
    'dash.js will parse the MPD manifest and attach it to the video element.': 'dash.js 会解析 MPD 清单并绑定到视频元素。',
    'Loading DASH playback engine.': '正在加载 DASH 播放引擎。',
    'dash.js is loaded only on the DASH player page.': 'dash.js 仅在 DASH 播放器页面加载。',
    'DASH playback error detected.': '检测到 DASH 播放错误。',
    'Check whether the MPD manifest and media segments are public and compatible with this browser.': '请检查 MPD 清单和媒体分片是否公开，并且兼容当前浏览器。',
    'DASH request may be blocked by browser CORS or access policy.': 'DASH 请求可能被浏览器 CORS 或访问策略阻止。',
    'DASH request was denied by the source server.': 'DASH 请求被源服务器拒绝。',
    'Check permissions, signed URL expiry, geo restrictions, DRM/license requirements, and whether the source allows browser playback from this site.': '请检查访问权限、签名 URL 是否过期、地区限制、DRM/许可要求，以及来源是否允许本站通过浏览器播放。',
    'DASH manifest or media segment was not found.': '未找到 DASH 清单或媒体分片。',
    'Check whether the MPD or segment URL is correct, still available, and not generated by an expired temporary link.': '请检查 MPD 或分片 URL 是否正确、仍然可用，并确认不是由已过期的临时链接生成。',
    'DASH source server or CDN error detected.': '检测到 DASH 源服务器或 CDN 错误。',
    'DASH manifest could not be loaded or parsed.': '无法加载或解析 DASH 清单。',
    'Verify that the MPD URL is public, valid XML, not an HTML error page, and served with browser-accessible CORS headers.': '请确认 MPD URL 公开、是有效 XML、不是 HTML 错误页，并且提供浏览器可访问的 CORS 响应头。',
    'DASH media segment could not be loaded.': '无法加载 DASH 媒体分片。',
    'Check segment URLs, CDN availability, CORS headers, token expiry, geo restrictions, and relative segment paths.': '请检查分片 URL、CDN 可用性、CORS 响应头、token 是否过期、地区限制和相对分片路径。',
    'DASH media compatibility issue detected.': '检测到 DASH 媒体兼容性问题。',
    'Check video/audio codecs, MIME types, and browser MediaSource support.': '请检查视频/音频编码、MIME 类型和浏览器 MediaSource 支持情况。',
    'DASH DRM or license issue detected.': '检测到 DASH DRM 或许可问题。',
    'Protected streams require a supported DRM license flow and cannot be tested as a plain public stream.': '受保护的视频流需要受支持的 DRM 许可流程，不能作为普通公开视频流测试。',
    'DASH network issue detected.': '检测到 DASH 网络问题。',
    'Check server availability, CORS headers, redirects, signed URL expiry, and network or CDN latency.': '请检查服务器可用性、CORS 响应头、重定向、签名 URL 是否过期，以及网络或 CDN 延迟。',
    'Playback appears stuck.': '播放似乎卡住了。',
    'The browser is waiting for video data and cannot continue smoothly.': '浏览器在等视频数据，暂时不能顺畅播放。',
    'Check the network, CORS, expired tokens, missing segments, or source server speed.': '请检查网络、CORS、过期 token、缺失分片或源服务器速度。',
    'Media is still loading.': '媒体仍在加载。',
    'The browser has not received enough information to start playback.': '浏览器还没拿到足够信息来开始播放。',
    'Check CORS, permissions, MIME type, network, and server availability.': '请检查 CORS、权限、MIME 类型、网络和服务器可用性。',
    'Media is still loading. Check CORS, network, MIME type, permissions, and server availability.': '媒体仍在加载。请检查 CORS、网络、MIME 类型、权限和服务器可用性。',
    'Playback could not start.': '播放无法开始。',
    'The browser did not receive playable media data in time.': '浏览器没有及时收到可播放的媒体数据。',
    'Check whether the link is public, CORS is allowed, the media format is supported, and the source server returns real media content.': '请检查链接是否公开、CORS 是否允许、格式是否受支持，以及服务器是否返回真实媒体内容。',
    'Playback appears stuck after repeated checks.': '播放多次检查后仍像是卡住了。',
    'Check missing segments, CORS, expired tokens, CDN delay, or source server overload.': '请检查分片缺失、CORS、token 过期、CDN 延迟或源服务器过载。',
    'Browser may be blocked from reading the HLS playlist.': '浏览器可能被拦截，无法读取 HLS 播放列表。',
    'Browser may be blocked from reading the HLS media segment.': '浏览器可能被拦截，无法读取 HLS 视频分片。',
    'Browser may be blocked from reading the HLS key.': '浏览器可能被拦截，无法读取 HLS 密钥。',
    'Browser may be blocked from reading the HLS resource.': '浏览器可能被拦截，无法读取 HLS 资源。',
    'Check permissions, expired tokens, and whether the source allows browser playback from this site.': '请检查权限、token 是否过期，以及来源是否允许本站播放。',
    'Check whether the URL is correct, still available, and not expired.': '请检查 URL 是否正确、仍可访问且未过期。',
    'HLS playlist server returned an error.': 'HLS 播放列表服务器返回错误。',
    'HLS media segment server returned an error.': 'HLS 视频分片服务器返回错误。',
    'HLS key server returned an error.': 'HLS 密钥服务器返回错误。',
    'HLS resource server returned an error.': 'HLS 资源服务器返回错误。',
    'Retry later, or check the source server/CDN logs if you own the stream.': '请稍后重试；如果你拥有该视频流，请检查源服务器或 CDN 日志。',
    'HLS playlist could not be loaded.': '无法加载 HLS 播放列表。',
    'Check that the M3U8 URL is public, not expired, and allows CORS.': '请确认 M3U8 URL 公开、未过期，并允许 CORS。',
    'HLS playlist is not valid.': 'HLS 播放列表格式不正确。',
    'Check that the URL returns a real M3U8 file, not an HTML error, login, redirect, or CDN page.': '请确认该 URL 返回真实 M3U8 文件，而不是错误页、登录页、重定向页或 CDN 页面。',
    'HLS video segment could not be loaded.': '无法加载 HLS 视频分片。',
    'Check segment URLs, CDN availability, CORS, token expiry, geo restrictions, and relative paths.': '请检查分片 URL、CDN、CORS、token 过期、地区限制和相对路径。',
    'HLS playback is buffering too long.': 'HLS 缓冲时间过长。',
    'Try another network or lower quality. The server may be slow or missing live segments.': '请尝试其他网络或较低清晰度；服务器可能较慢或缺少直播分片。',
    'This HLS stream may require DRM or a key license.': '这个 HLS 流可能需要 DRM 或密钥授权。',
    'Protected streams need a supported DRM/license flow and cannot be tested as plain public streams.': '受保护视频需要 DRM/授权流程，不能当作普通公开视频测试。',
    'The browser could not decode this HLS media.': '浏览器无法解码这个 HLS 视频。',
    'Check codecs, browser support, and unsupported audio/video tracks.': '请检查编码、浏览器支持，以及是否有不受支持的音视频轨道。',
    'HLS network request failed.': 'HLS 网络请求失败。',
    'Check server availability, CORS, redirects, signed URL expiry, mixed content, or network filters.': '请检查服务器、CORS、重定向、签名 URL 过期、混合内容或网络过滤。',
    'MEDIA_ERR_ABORTED: playback was stopped by the user or browser.': 'MEDIA_ERR_ABORTED：播放被用户或浏览器停止。',
    'MEDIA_ERR_NETWORK: network loading failed.': 'MEDIA_ERR_NETWORK：网络加载失败。',
    'MEDIA_ERR_DECODE: the browser could not decode this media.': 'MEDIA_ERR_DECODE：浏览器无法解码这个媒体。',
    'MEDIA_ERR_SRC_NOT_SUPPORTED: this browser cannot play this source or format.': 'MEDIA_ERR_SRC_NOT_SUPPORTED：浏览器无法播放这个来源或格式。',
    'Check server availability, CORS, signed URL expiry, redirects, mixed content, and network connectivity.': '请检查服务器、CORS、签名 URL 过期、重定向、混合内容和网络连接。',
    'Check that the file uses browser-supported audio/video codecs and is not damaged.': '请检查文件编码是否受浏览器支持，并确认文件没有损坏。',
    'Try a public MP4 file, or check format, MIME type, codec, and Range requests.': '请尝试公开 MP4 文件，或检查格式、MIME 类型、编码和 Range 请求。',
    'Check that the URL is public or authorized, has correct CORS/MIME headers, and is browser-compatible.': '请确认 URL 公开或已授权，CORS/MIME 响应头正确，并兼容当前浏览器。',
    'Browser may be blocked from reading the DASH stream.': '浏览器可能被拦截，无法读取 DASH 视频流。',
    'Source server denied the DASH request.': '源服务器拒绝了 DASH 请求。',
    'Check permissions, expired signed URLs, geo restrictions, DRM, and browser playback rules.': '请检查权限、签名 URL 过期、地区限制、DRM 和浏览器播放规则。',
    'DASH manifest or video segment was not found.': '未找到 DASH 清单或视频分片。',
    'Check whether the MPD or segment URL is correct, available, and not expired.': '请检查 MPD 或分片 URL 是否正确、可访问且未过期。',
    'DASH source server or CDN returned an error.': 'DASH 源服务器或 CDN 返回错误。',
    'DASH manifest could not be loaded or read.': '无法加载或读取 DASH 清单。',
    'Check that the MPD URL is public, valid XML, not an HTML error page, and allows CORS.': '请确认 MPD URL 公开、是有效 XML、不是 HTML 错误页，并允许 CORS。',
    'DASH video segment could not be loaded.': '无法加载 DASH 视频分片。',
    'The browser may not support this DASH media.': '浏览器可能不支持这个 DASH 媒体。',
    'Check codecs, MIME type, and browser MediaSource support.': '请检查编码、MIME 类型和浏览器 MediaSource 支持。',
    'This DASH stream may require DRM or a license.': '这个 DASH 流可能需要 DRM 或授权。',
    'DASH network request failed.': 'DASH 网络请求失败。',
    'Check server availability, CORS, redirects, signed URL expiry, and CDN/network delay.': '请检查服务器、CORS、重定向、签名 URL 过期以及 CDN/网络延迟。',
  },
  patterns: [
    {
      match: '^Browser may be blocked from reading the HLS (.+)\.$',
      replace: '浏览器可能被拦截，无法读取 HLS $1。',
    },
    {
      match: '^HLS (.+) server returned an error\.$',
      replace: 'HLS $1 服务器返回错误。',
    },
    {
      match: '^(.+) diagnostic started\\. Playback depends on browser support, codec support, CORS and server access settings\\.$',
      replace: '$1诊断已开始。播放结果取决于浏览器支持、编码支持、CORS 和服务器访问设置。',
    },
    {
      match: '^Checking (.+) playback with (.+)\\.$',
      replace: '正在使用 $2 检查 $1 播放。',
    },
    {
      match: '^Selected playback engine: (.+)\\.$',
      replace: '已选择播放引擎：$1。',
    },
    {
      match: '^Detected URL type: (.+)\\.$',
      replace: '检测到链接类型：$1。',
    },
    {
      match: '^Duration: unknown duration\\. Resolution: unknown resolution\\.$',
      replace: '时长：未知。分辨率：未知。',
    },
    {
      match: '^Duration: unknown duration\\. Resolution: (.+)\\.$',
      replace: '时长：未知。分辨率：$1。',
    },
    {
      match: '^Duration: (.+)\\. Resolution: unknown resolution\\.$',
      replace: '时长：$1。分辨率：未知。',
    },
    {
      match: '^Duration: (.+)\\. Resolution: (.+)\\.$',
      replace: '时长：$1。分辨率：$2。',
    },
    {
      match: '^(.+) source loaded\\. Use the video controls if the browser blocks automatic playback\\.$',
      replace: '$1来源已加载。如果浏览器阻止自动播放，请使用视频控件开始播放。',
    },
    {
      match: "^Technical details: play\\(\\) failed because the user didn't interact with the document first\\. \\[filtered-url\\]$",
      replace: '技术详情：浏览器要求用户先与页面交互后才能播放。[filtered-url]',
    },
    {
      match: '^Technical details: Failed to load because no supported source was found\\.?$',
      replace: '技术详情：加载失败，没有找到浏览器支持的媒体来源。',
    },
    {
      match: '^Technical details: No supported source was found\\.?$',
      replace: '技术详情：没有找到浏览器支持的媒体来源。',
    },
    {
      match: '^Technical details: The element has no supported sources\\.?$',
      replace: '技术详情：该视频元素没有可用的受支持媒体来源。',
    },
    {
      match: '^Technical details: /?MEDIA_ERR_SRC_NOT_SUPPORTED\\.?$',
      replace: '技术详情：MEDIA_ERR_SRC_NOT_SUPPORTED，当前浏览器不支持该媒体来源。',
    },
    {
      match: '^/?MEDIA_ERR_SRC_NOT_SUPPORTED\\.?$',
      replace: 'MEDIA_ERR_SRC_NOT_SUPPORTED：当前浏览器不支持该媒体来源。',
    },
    {
      match: '^Technical details: The media could not be loaded, either because the server or network failed or because the format is not supported\\.?$',
      replace: '技术详情：媒体无法加载，可能是服务器或网络失败，也可能是媒体格式不受当前浏览器支持。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), no HTTP response status, message=Failed to load because no supported source was found\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，未收到 HTTP 响应状态，错误信息=没有找到浏览器支持的媒体来源。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), HTTP (.+), message=Failed to load because no supported source was found\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，HTTP $4，错误信息=没有找到浏览器支持的媒体来源。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), no HTTP response status, message=(.+)\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，未收到 HTTP 响应状态，错误信息=$4。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), HTTP (.+), message=(.+)\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，HTTP $4，错误信息=$5。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), no HTTP response status\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，未收到 HTTP 响应状态。',
    },
    {
      match: '^Technical details: type=(.+), details=(.+), fatal=(true|false), HTTP (.+)\\.$',
      replace: '技术详情：类型=$1，详情=$2，严重错误=$3，HTTP $4。',
    },
    {
      match: '^Technical details: code=(.+), (.+), HTTP (.+)\\.$',
      replace: '技术详情：错误码=$1，$2，HTTP $3。',
    },
    {
      match: '^Technical details: (.+), HTTP (.+)\\.$',
      replace: '技术详情：$1，HTTP $2。',
    },
    {
      match: '^Technical details: (.+)$',
      replace: '技术详情：$1',
    },
    {
      match: '^(.+) asked the browser to start playback\\.$',
      replace: '$1 已请求浏览器开始播放。',
    },
    {
      match: '^HLS quality switched to (.+)\\.$',
      replace: 'HLS 清晰度已切换到 $1。',
    },
    {
      match: '^HLS media segment loaded #(.+)\\.$',
      replace: 'HLS 媒体分片已加载 #$1。',
    },
    {
      match: '^(.+) variant stream(s)? found\\.$',
      replace: '发现 $1 个变体流。',
    },
    {
      match: '^(.+) quality level(s)? available for adaptive playback\\.$',
      replace: '发现 $1 个可用于自适应播放的清晰度级别。',
    },
    {
      match: '^(.+) will use the browser built-in media pipeline\\.$',
      replace: '$1 将使用浏览器内置媒体管线。',
    },
    {
      match: '^DASH quality rendered: (.+)\\.$',
      replace: 'DASH 已渲染清晰度：$1。',
    },
  ],
};

export default zhCNPlayerLogText;
